{-
functions for time converter
definition of timetuple
(Int, Int, Int, Int, Int, Int, String)
example : datesample
(2014, 3, 17, 16, 15, 12, "JST")

generated by T.Yokozawa Jun.24. 2014

-}


module HasKAL.TimeUtils.TimeConvert
( getYear
, getMonth
, getDay
, getHour
, getMinute
, getSecond
, getTimeZone
) where 

getYear :: (Int, Int, Int, Int, Int, Int, String)->Int
getYear (a,_,_,_,_,_,_)=a

getMonth :: (Int, Int, Int, Int, Int, Int, String)->Int
getMonth (_,a,_,_,_,_,_)=a

getDay :: (Int, Int, Int, Int, Int, Int, String)->Int
getDay (_,_,a,_,_,_,_)=a

getHour :: (Int, Int, Int, Int, Int, Int, String)->Int
getHour (_,_,_,a,_,_,_)=a

getMinute :: (Int, Int, Int, Int, Int, Int, String)->Int
getMinute (_,_,_,_,a,_,_)=a

getSecond :: (Int, Int, Int, Int, Int, Int, String)->Int
getSecond (_,_,_,_,_,a,_)=a

getTimeZone :: (Int, Int, Int, Int, Int, Int, String)->String
getTimeZone (_,_,_,_,_,_,a)=a


{-
sample output Jun.24. 2014

*Main> datesample
(2014,3,17,16,15,12,"JST")
*Main> getYear datesample
2014
*Main> getMonth datesample
3
*Main> getDay datesample
17
*Main> getHour datesample
16
*Main> getMinute datesample
15
*Main> getSecond datesample
12
*Main> getTimeZone datesample
"JST"

-}